# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
from openerp import api, fields, models

class documento(models.Model):
    """Tabla Documentos"""
    _name = 'documento'
    _rec_name = 'titulo'
    carpeta_id = fields.Many2one('carpeta','Carpeta')
    codigo = fields.Integer('Código', size=12, required=True, help='Código del Documento')
    titulo = fields.Char('Título', size=200, required=True, help='Título del Documento')
    fecha_ela = fields.Date('Elaboración', required=True, help='Fecha de Elaboración del Documento')
    productor_id = fields.Many2one('productor', 'Produtor', required=True, help='Nombre del Productor del Documento')
    materia_id = fields.Many2one('materia', 'Materia', required=True, help='Nombre de la Materia del Documento')
    tipologia_id = fields.Many2one('tipologia', 'Tipología', required=True, help='Tipo de Documento')
    descripcion = fields.Text('Descripción')
    adjunto = fields.Binary('Adjunto')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código del Documento ya se encuetra Registrado !'),
    ]

class carpeta(models.Model):
    """Tabla Carpetas"""
    _name = 'carpeta'
    _rec_name = 'nombre'
    documento_ids = fields.One2many('documento','carpeta_id','Documentos')
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Carpeta')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Carpeta')
    fecha_ini = fields.Date('Fecha Inicio', required=True, help='Fecha de Creación de la Carpeta')
    fecha_fin = fields.Date('Fecha Fin', required=True, help='Fecha de Cierre de la Carpeta')
    descripcion = fields.Text('Descripción')
#   """Ubicación Física"""
    vagon_id = fields.Many2one('vagon', 'Vagón', required=True, help='Nombre del Vagón')
    modulo_id = fields.Many2one('modulo', 'Módulo', required=True, help='Nombre del Módulo')
    peldano_id = fields.Many2one('peldano', 'Peldaño', required=True, help='Nombre del Peldaño')
    caja_id = fields.Many2one('caja', 'Caja', required=True, help='Nombre de la Caja')
#   """Ubicación Geográfica"""
    estado_id = fields.Many2one('ubc_estados', 'Entidad', required=True, help='Nombre de la Entidad')
    municipio_id = fields.Many2one('ubc_municipios', 'Municipio', required=True, help='Nombre del Municipio')
    parroquia_id = fields.Many2one('ubc_parroquias', 'Parroquia', required=True, help='Nombre de la Parroquia')
#   """Ubicación Administrativa"""
    organismo_id = fields.Many2one('organismo', 'Organismo', required=True, help='Nombre de la Organismo')
    gerencia_id = fields.Many2one('gerencia', 'Gerencia', required=True, help='Nombre de la Gerencia')

#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Carpeta ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Carpeta ya se encuetra Registrado !'),
    ]

class organismo(models.Model):
    """Tabla Organismos"""
    _name = 'organismo'
    _rec_name = 'nombre'
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Organismo')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Organismo')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Organismo ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Organismo ya se encuetra Registrado !'),
    ]

class gerencia(models.Model):
    """Tabla Gerencias"""
    _name = 'gerencia'
    _rec_name = 'nombre'
    organismo_id = fields.Many2one('organismo', 'Organismo', required=True, help='Nombre del Organismo')
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Gerencia')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Gerencia')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Gerencia ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Gerencia ya se encuetra Registrado !'),
    ]

class vagon(models.Model):
    """Tabla Vagones"""
    _name = 'vagon'
    _rec_name = 'nombre'
    codigo = fields.Integer('Código', size=12, required=True, help='Código del Vagón')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre del Vagón')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código del Vagón ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre del Vagón ya se encuetra Registrado !'),
    ]

class modulo(models.Model):
    """Tabla Módulos"""
    _name = 'modulo'
    _rec_name = 'nombre'
    vagon_id = fields.Many2one('vagon', 'Vagón', required=True, help='Nombre del Vagón')
    codigo = fields.Integer('Código', size=12, required=True, help='Código del Módulo')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre del Módulo')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código del Módulo ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre del Módulo ya se encuetra Registrado !'),
    ]

class peldano(models.Model):
    """Tabla Peldaños"""
    _name = 'peldano'
    _rec_name = 'nombre'
    modulo_id = fields.Many2one('modulo', 'Módulo', required=True, help='Nombre del Módulo')
    codigo = fields.Integer('Código', size=12, required=True, help='Código del Peldaño')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre del Peldaño')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código del Peldaño ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre del Peldaño ya se encuetra Registrado !'),
    ]

class caja(models.Model):
    """Tabla Cajas"""
    _name = 'caja'
    _rec_name = 'nombre'
    peldano_id = fields.Many2one('peldano', 'Peldaño', required=True, help='Nombre del Peldaño')
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Caja')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Caja')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Caja ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Caja ya se encuetra Registrado !'),
    ]

class tipologia(models.Model):
    """Tabla Tipología"""
    _name = 'tipologia'
    _rec_name = 'nombre'
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Tipología')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Tipología')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Tipología ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Tipología ya se encuetra Registrado !'),
    ]

class productor(models.Model):
    """Tabla Productor(es)"""
    _name = 'productor'
    _rec_name = 'nombre'
    codigo = fields.Integer('Código', size=12, required=True, help='Código del Productor')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre del Productor')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código del Productor ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre del Productor ya se encuetra Registrado !'),
    ]

class materia(models.Model):
    """Tabla Materias"""
    _name = 'materia'
    _rec_name = 'nombre'
    codigo = fields.Integer('Código', size=12, required=True, help='Código de la Materia')
    nombre = fields.Char('Nombre', size=200, required=True, help='Nombre de la Materia')
#   """Restrinciones"""
    _sql_constraints = [
        ('che_codigo', 'unique(codigo)', 'El Código de la Materia ya se encuetra Registrado !'),
        ('che_nombre', 'unique(nombre)', 'El Nombre de la Materia ya se encuetra Registrado !'),
    ]